{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zta-operator.fullname" . }}-binding
  labels:
    {{- include "zta-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zta-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "zta-operator.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
