{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zta-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zta-operator.labels" . | nindent 4 }}
{{- end }}
