apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zta-operator-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["devsecops.licenta.ro"]
    resources: ["zerotrustapplications", "zerotrustapplications/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["devsecops.licenta.ro"]
    resources: ["zerotrustsecrets", "zerotrustsecrets/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["devsecops.licenta.ro"]
    resources: ["supplychainattestations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "events", "secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["security.istio.io"]
    resources: ["authorizationpolicies"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["extensions.istio.io"]
    resources: ["wasmplugins"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
