apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zta-operator-falco-talon-configmap
  namespace: falco-talon
subjects:
  - kind: ServiceAccount
    name: zta-operator
    namespace: devsecops-system
roleRef:
  kind: Role
  name: zta-operator-falco-talon-configmap
  apiGroup: rbac.authorization.k8s.io
