apiVersion: apps/v1
kind: Deployment
metadata:
  name: zta-operator
  namespace: devsecops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zta-operator
  template:
    metadata:
      labels:
        app: zta-operator
    spec:
      serviceAccountName: zta-operator
      containers:
        - name: operator
          image: ghcr.io/sabinghost19/zta-operator:v0.1.0
          imagePullPolicy: IfNotPresent
          command:
            ["kopf", "run", "--all-namespaces", "-m", "zta_operator.operator"]
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: TALON_NAMESPACE
              value: falco-talon
            - name: TALON_CONFIGMAP_NAME
              value: falco-talon-rules
            - name: TALON_CONFIGMAP_KEY
              value: rules.yaml
